### ISSUE TITLE
Total energy consumption is 0

### ISSUE THREAD

**Issue by ghost** [Heckie75/voltcraft-sem-6000#6] opened 2020-04-21 03:01 UTC
The app reads out the real total consumption, this script doesnt

**Comment by Heckie75** [comment] 2020-05-25 17:00
This issue is a duplicate of #2 

I guess that this script is correct and the app is wrong. The app calculates the total consumption by adding up all records per month instead of using the value coming from device's API. It is correct that I haven't seen something else than zero returned by the API yet. Maybe this is a firmware bug and that is the reason why the app displays a value based on recorded data. 

However, I have just pushed a new version to github. After you have requested specific data by calling "--data xxx" and then print the status, you get a line called _total last xxx_

Example:
~/voltcraft-sem-6000$ sem-6000 K --data day --status --print
        Status:
          Power:                off
          Voltage:              237 VAC
          Ampere:               0.0 A
          Watts:                0.0 W
          Frequency:            50 Hz
          Power factor:         1
          Total consumption:    0.0 kWh
          Total last 24h:       3 Wh

It works also with JSON output.

**Closed as completed** 2020-08-04 05:29 UTC
